---
proxy-providers:
  Akun-Oracle:
    type: file
    path: "./proxy_provider/oracle.yml"
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 120
  Akun-Indo:
    type: file
    path: "./proxy_provider/indo.yml"
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 300
proxy-groups:
- name: Pew
  type: select
  disable-udp: false
  proxies:
  - Oracle
  - TrafficIndo
  - TrafficSosmed
  - TrafficStream
  - TrafficDirect
  use:
  - Akun-Oracle
  - Akun-Indo
  url: http://cp.cloudflare.com/generate_204
  interval: '180'
- name: Oracle
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - Akun-Oracle
  url: http://cp.cloudflare.com/generate_204
  interval: '300'
- name: TrafficIndo
  type: select
  disable-udp: false
  use:
  - Akun-Indo
  proxies:
  - TrafficDirect
  url: http://cp.cloudflare.com/generate_204
  interval: '300'
- name: TrafficGame
  type: select
  disable-udp: false
  use:
  - Akun-Indo
  proxies:
  - TrafficDirect
- name: TrafficSosmed
  #type: load-balance
  #strategy: round-robin
  type: fallback
  lazy: true
  disable-udp: false
  use:
  - Akun-Oracle
  - Akun-Indo
  url: http://cp.cloudflare.com/generate_204
  interval: '30'
- name: TrafficStream
  #type: load-balance
  #strategy: round-robin
  type: fallback
  lazy: true
  disable-udp: false
  filter: VLess|Trojan|Bijinet
  use:
  - Akun-Oracle
  - Akun-Indo
  url: http://cp.cloudflare.com/generate_204
  interval: '30'
- name: TrafficDirect
  type: select
  disable-udp: false
  proxies:
  - DIRECT
- name: TrafficAds
  type: select
  proxies:
  - REJECT
  - TrafficDirect
  - Pew
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  listen: 0.0.0.0:7874
  fake-ip-filter:
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - time1.cloud.tencent.com
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "*.music.migu.cn"
  - music.migu.cn
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - msftconnecttest.com
  - msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - "+.srv.nintendo.net"
  - "*.n.n.srv.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.*.microsoft.com
  - "*.*.xboxlive.com"
  - xbox.*.microsoft.com
  - xnotify.xboxlive.com
  - "+.battlenet.com.cn"
  - "+.wotgame.cn"
  - "+.wggames.cn"
  - "+.wowsgame.cn"
  - "+.wargaming.net"
  - proxy.golang.org
  - stun.*.*
  - stun.*.*.*
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - "+.stun.*.*.*.*.*"
  - heartbeat.belkin.com
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "*.router.asus.com"
  - mesu.apple.com
  - swscan.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - lens.l.google.com
  - stun.l.google.com
  - "+.nflxvideo.net"
  - "*.square-enix.com"
  - "*.finalfantasyxiv.com"
  - "*.ffxiv.com"
  - "*.ff14.sdo.com"
  - ff.dorado.sdo.com
  - "*.mcdn.bilivideo.cn"
  - "+.media.dssott.com"
  - time-ios.apple.com
  - shark007.net
  fallback-filter:
    geoip: true
    geoip-code: ID
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
    domain:
    - "+.google.com"
    - "+.facebook.com"
    - "+.youtube.com"
    - "+.githubusercontent.com"
    - "+.googlevideo.com"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - msftconnecttest.com
    - msftncsi.com
    - "+.*"
  default-nameserver:
  - 8.8.8.8
  - 8.8.4.4
  - 1.1.1.1
  - 1.0.0.1
  - 9.9.9.9
  - 149.112.112.112
  - 208.67.222.222
  - 208.67.220.220
  - 185.228.168.9
  - 185.228.169.168
  - 76.76.2.0
  - 76.76.10.0
  - 94.140.14.140
  - 94.140.14.141
  - 172.105.216.54
  nameserver:
  - 1.1.1.1
  - 8.8.8.8
  - 9.9.9.9
  fallback:
  - 1.1.1.1
  - 8.8.8.8
  - 9.9.9.9
  prefer-h3: false
  fake-ip-range: 198.18.0.1/16
redir-port: 7892
tproxy-port: 7895
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
unified-delay: true
external-controller: 0.0.0.0:9090
secret: '123456'
bind-address: "*"
external-ui: "/usr/share/openclash/ui"
ipv6: true
profile:
  store-selected: true
  store-fake-ip: true
rules:
- AND,((GEOSITE,YOUTUBE),(NETWORK,UDP)),REJECT
- GEOSITE,CATEGORY-ADS-ALL,TrafficAds
- GEOSITE,openai,TrafficIndo
- RULE-SET,TrafficIndonesia,TrafficIndo
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- DST-PORT,22,TrafficDirect
- RULE-SET,rule_lancidr,DIRECT,no-resolve
- RULE-SET,rule_falsepositive,Pew
- RULE-SET,rule_malicious,REJECT
- RULE-SET,rule_maliciousip,REJECT
- RULE-SET,rule_personalads,TrafficAds
- RULE-SET,rule_basicads,TrafficAds
- RULE-SET,rule_hijacking,TrafficAds
- RULE-SET,rule_privacy,TrafficAds
- RULE-SET,rule_Direct,TrafficDirect
- RULE-SET,rule_playstore,Pew
- RULE-SET,rule_disneyplus,TrafficIndo
- RULE-SET,rule_netflix,TrafficIndo
- RULE-SET,rule_Indo,TrafficIndo
- RULE-SET,rule_hbo,TrafficIndo
- RULE-SET,rule_hboasia,TrafficIndo
- RULE-SET,rule_hbohk,TrafficIndo
- RULE-SET,rule_hbousa,TrafficIndo
- RULE-SET,rule_TrafficStreaming,TrafficStream
- RULE-SET,rule_iqiyi,TrafficStream
- RULE-SET,rule_iqiyiinter,TrafficStream
- RULE-SET,rule_primevideo,TrafficStream
- RULE-SET,rule_twitch,TrafficStream
- RULE-SET,rule_Youtube,TrafficStream
- RULE-SET,rule_Sosmed,TrafficSosmed
- RULE-SET,rule_line,TrafficSosmed
- RULE-SET,rule_metaverse,TrafficSosmed
- RULE-SET,rule_tiktok,TrafficSosmed
- RULE-SET,rule_twitter,TrafficSosmed
- RULE-SET,rule_telegram,TrafficSosmed
- RULE-SET,rule_telegramcidr,TrafficSosmed
- RULE-SET,rule_videoconferences,TrafficStream
- RULE-SET,rule_portgames,TrafficGame
- RULE-SET,rule_Gaming,TrafficGame
- RULE-SET,rule_games,TrafficGame
- RULE-SET,rule_discord,TrafficIndo
- RULE-SET,rule_umum,Pew
- MATCH,Pew

script:
  shortcuts:
    TCPgames: network == 'tcp' and dst_port not in [21, 22, 23, 53, 80, 123, 143, 194, 443, 465, 587, 853, 993, 995, 998, 2052, 2053, 2082, 2083, 2086, 2095, 2096, 5222, 5228, 5229, 5230, 8080, 8443, 8880, 8883, 8888, 8889]
    UDPgames: network == 'udp' and dst_port not in [21, 22, 23, 53, 80, 123, 143, 194, 443, 465, 587, 853, 993, 995, 998, 2052, 2053, 2082, 2083, 2086, 2095, 2096, 5222, 5228, 5229, 5230, 8080, 8443, 8880, 8883, 8888, 8889]
    speedtest: network == "tcp" and match_provider("rule_Speedtest")
geodata-mode: false
geodata-loader: memconservative
tcp-concurrent: true
find-process-mode: 'off'
global-client-fingerprint: none
authentication:
- Clash:H7M5JdKt
tun:
  enable: true
  stack: system
  device: utun
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
  - tcp://any:53
rule-providers:
  TrafficIndonesia:
    type: file
    behavior: classical
    path: "./rule_provider/Indonesia.yml"
  rule_Direct:
    type: file
    behavior: classical
    path: "./rule_provider/rule_direct.yaml"
  rule_umum:
    type: http
    behavior: classical
    path: "./rule_provider/rule_umum.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_umum.yaml
    interval: 86400
  rule_portgames:
    type: http
    behavior: classical
    path: "./rule_provider/rule_portgames.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_portgames.yaml
    interval: 86400
  rule_videoconferences:
    type: http
    behavior: classical
    path: "./rule_provider/rule_videoconferences.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_videoconferences.yaml
    interval: 86400
  rule_Indo:
    type: http
    behavior: classical
    path: "./rule_provider/rule_indo.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_indo.yaml
    interval: 86400
  rule_Sosmed:
    type: http
    behavior: classical
    path: "./rule_provider/rule_sosmed.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_sosmed.yaml
    interval: 86400
  rule_TrafficStreaming:
    type: http
    behavior: classical
    path: "./rule_provider/rule_TrafficStreaming.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_TrafficStreaming.yaml
    interval: 86400
  rule_Gaming:
    type: http
    behavior: classical
    path: "./rule_provider/rule_gaming.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_gaming.yaml
    interval: 86400
  rule_Speedtest:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_speedtest.yaml
    path: "./rule_provider/rule_speedtest.yaml"
    interval: 86400
  rule_discord:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_discord.yaml
    path: "./rule_provider/rule_discord.yaml"
    interval: 86400
  rule_hijacking:
    type: http
    behavior: classical
    path: "./rule_provider/rule_hijacking.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_hijacking.yaml
    interval: 86400
  rule_privacy:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_privacy.yaml
    path: "./rule_provider/rule_privacy.yaml"
    interval: 86400
  rule_basicads:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_basicads.yaml
    path: "./rule_provider/rule_basicads.yaml"
    interval: 43200
  rule_personalads:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_personalads.yaml
    path: "./rule_provider/rule_personalads.yaml"
    interval: 86400
  rule_malicious:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_malicious.yaml
    path: "./rule_provider/rule_malicious.yaml"
    interval: 43200
  rule_maliciousip:
    type: http
    behavior: ipcidr
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_maliciousip.yaml
    path: "./rule_provider/rule_maliciousip.yaml"
    interval: 43200
  rule_falsepositive:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_falsepositive.yaml
    path: "./rule_provider/rule_falsepositive.yaml"
    interval: 86400
  rule_porn:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_porn.yaml
    path: "./rule_provider/rule_porn.yaml"
    interval: 86400
  rule_nsfw:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_nsfw.yaml
    path: "./rule_provider/rule_nsfw.yaml"
    interval: 43200
  rule_lancidr:
    type: http
    behavior: ipcidr
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_lancidr.yaml
    path: "./rule_provider/rule_lancidr.yaml"
    interval: 86400
  rule_telegramcidr:
    type: http
    behavior: ipcidr
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_telegramcidr.yaml
    path: "./rule_provider/rule_telegramcidr.yaml"
    interval: 86400
  rule_telegram:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_telegram.yaml
    path: "./rule_provider/rule_telegram.yaml"
    interval: 86400
  rule_disneyplus:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_disneyplus.yaml
    path: "./rule_provider/rule_disneyplus.yaml"
    interval: 86400
  rule_games:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_games.yaml
    path: "./rule_provider/rule_games.yaml"
    interval: 86400
  rule_hbo:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_hbo.yaml
    path: "./rule_provider/rule_hbo.yaml"
    interval: 86400
  rule_hboasia:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_hboasia.yaml
    path: "./rule_provider/rule_hboasia.yaml"
    interval: 86400
  rule_hbohk:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_hbohk.yaml
    path: "./rule_provider/rule_hbohk.yaml"
    interval: 86400
  rule_hbousa:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_hbousa.yaml
    path: "./rule_provider/rule_hbousa.yaml"
    interval: 86400
  rule_iqiyi:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_iqiyi.yaml
    path: "./rule_provider/rule_iqiyi.yaml"
    interval: 86400
  rule_iqiyiinter:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_iqiyiinter.yaml
    path: "./rule_provider/rule_iqiyiinter.yaml"
    interval: 86400
  rule_line:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_line.yaml
    path: "./rule_provider/rule_line.yaml"
    interval: 86400
  rule_metaverse:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_metaverse.yaml
    path: "./rule_provider/rule_metaverse.yaml"
    interval: 86400
  rule_netflix:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_netflix.yaml
    path: "./rule_provider/rule_netflix.yaml"
    interval: 86400
  rule_primevideo:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_primevideo.yaml
    path: "./rule_provider/rule_primevideo.yaml"
    interval: 86400
  rule_playstore:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_playstore.yaml
    path: "./rule_provider/rule_playstore.yaml"
    interval: 86400
  rule_tiktok:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_tiktok.yaml
    path: "./rule_provider/rule_tiktok.yaml"
    interval: 86400
  rule_twitch:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_twitch.yaml
    path: "./rule_provider/rule_twitch.yaml"
    interval: 86400
  rule_twitter:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_twitter.yaml
    path: "./rule_provider/rule_twitter.yaml"
    interval: 86400
  rule_Youtube:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_youtube.yaml
    path: "./rule_provider/rule_youtube.yaml"
    interval: 86400
